import streamlit as st
import requests
import os

try:
    API_URL = st.secrets.get("API_URL", os.getenv("API_URL", "http://127.0.0.1:8080"))
except Exception:
    API_URL = os.getenv("API_URL", "http://127.0.0.1:8080") 

# --- 1. CLAUDE-INSPIRED GLASSMORPHISM CSS ---
st.set_page_config(page_title="HarBr | Trust Infrastructure", layout="centered")

st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Fraunces:wght@400;600&family=Inter:wght@400;600&display=swap');

    /* Global Theme */
    .stApp {
        background-color: #121212 !important;
        color: #E0E0E0 !important;
        font-family: 'Inter', sans-serif;
    }

    /* Chat Styling */
    .stChatMessage {
        background: rgba(255, 255, 255, 0.03) !important;
        backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.08) !important;
        border-radius: 15px !important;
        padding: 20px !important;
        margin-bottom: 15px !important;
    }

    /* Pastel Yellow Accents */
    h1, h2, h3, .stMarkdown strong {
        color: #F9E076 !important;
        font-family: 'Inter', sans-serif;
    }

    /* Serif for AI "Thinking" and Audit Content */
    .serif-text {
        font-family: 'Fraunces', serif;
        font-size: 1.1rem;
        line-height: 1.6;
    }

    /* Hide Streamlit elements */
    header, footer {visibility: hidden;}
    
    /* Input Box styling */
    .stChatInputContainer {
        padding-bottom: 2rem;
    }
    
    /* Glass Card for Properties generated by AI */
    .glass-card {
        background: rgba(255, 255, 255, 0.03);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 12px;
        padding: 20px;
        margin-bottom: 15px;
        transition: border 0.3s ease;
    }
    .glass-card:hover {
        border: 1px solid #F9E076; /* The Pastel Yellow Glow */
    }
</style>
""", unsafe_allow_html=True)

# --- 2. THE CHAT INTERFACE ---

if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Welcome to HarBr. I can help you find a home, list your property, or audit the legality of rental demands. How shall we begin?", "thinking": []}
    ]

# Display chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message.get("thinking"):
            with st.expander("View Agent Thinking Process"):
                for step in message["thinking"]:
                    st.write(f"**Agent**: {step['agent']}")
                    st.write(f"**Function Executed**: `{step['function']}`")
                    st.write(f"**Parameters**: {step['args']}")
                    st.divider()

        # Wrap content in a serif div if it's the assistant
        if message["role"] == "assistant":
            st.markdown(f'<div class="serif-text">{message["content"]}</div>', unsafe_allow_html=True)
        else:
            st.markdown(message["content"])

# User Input
if prompt := st.chat_input("Ask about a property, list your home, or check legalities..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # --- 3. THE GEMINI "BRAIN" ---
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                payload = {"messages": [{"role": m["role"], "content": m["content"]} for m in st.session_state.messages]}
                res = requests.post(f"{API_URL}/orchestrator/chat", json=payload)
                res.raise_for_status()
                data = res.json()
                full_response = data["reply"]
                thinking_process = data.get("thinking_process", [])
            except Exception as e:
                full_response = f"Connection to HarBr Brain failed: {e}"
                thinking_process = []
            
            if thinking_process:
                with st.expander("View Agent Thinking Process"):
                    for step in thinking_process:
                        st.write(f"**Agent**: {step['agent']}")
                        st.write(f"**Function Executed**: `{step['function']}`")
                        st.write(f"**Parameters**: {step['args']}")
                        st.divider()
                        
            st.markdown(f'<div class="serif-text">{full_response}</div>', unsafe_allow_html=True)
            
    st.session_state.messages.append({"role": "assistant", "content": full_response, "thinking": thinking_process})
